import React from "react";

export const metadata = {
  title: "Privacy Policy | PawZcozy",
  description: "Generated by create next app",
};

export default function layout({ children }) {
  return (
    <div className="w-full flex items-center justify-center bg-surface py-10">
      {children}
    </div>
  );
}
