import React from "react";

export const metadata = {
  title: "PawZcozy | About",
  description: "Generated by create next app",
};

export default function layout({ children }) {
  return (
    <div className="w-full flex flex-col items-center bg-surface">
      {children}
    </div>
  );
}
