import Provider from "@/app/components/TemplateComponents/Provider";
import "./globals.css";
import Footer from "./components/TemplateComponents/Footer";
import Header from "./components/TemplateComponents/Header";
import FooterChildren from "./components/TemplateComponents/FooterChildren";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "Home | PawZcozy ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Provider>
          <div
            className="flex flex-col bg-surface-surfaceContainerHighest relative"
            style={{ height: "100%", width: "100%" }}
          >
            <Header>
            <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7596111115934322"
            crossorigin="anonymous"></script>
            </Header>
                      
            <NextTopLoader
              color="#2299DD"
              initialPosition={0.08}
              crawlSpeed={200}
              height={3}
              crawl={true}
              showSpinner={true}
              easing="ease"
              speed={200}
              zIndex={1600}
            />
            {children}
            <Footer>
              <FooterChildren />
            </Footer>
          </div>
        </Provider>
      </body>
    </html>
  );
}
