import Provider from "@/app/components/TemplateComponents/Provider";
import "./globals.css";
import Footer from "./components/TemplateComponents/Footer";
import Header from "./components/TemplateComponents/Header";
import FooterChildren from "./components/TemplateComponents/FooterChildren";

export const metadata = {
  title: "PawZcozy | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Provider>
          <div
            className="flex flex-col bg-surface-surfaceContainerHighest relative"
            style={{ height: "100%", width: "100%" }}
          >
            <Header />
            {children}
            <Footer>
              <FooterChildren />
            </Footer>
          </div>
        </Provider>
      </body>
    </html>
  );
}
